name: wajba_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  introduction_screen: ^3.1.17
  intl_phone_field: ^3.2.0
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  badges: ^3.1.2
  video_player: ^2.9.5
  pinput: ^5.0.1
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_sliders: ^29.1.35
  slidable_button: ^3.0.0+1
  persistent_bottom_nav_bar: ^6.2.1
  country_picker:
    path: ./country_picker-2.0.27

  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/Video/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500

    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf
          style: italic
          weight: 200
        - asset: assets/fonts/GeneralSans-Italic.otf
          style: italic
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-SemiboldItalic.otf
          style: italic
          weight: 600