name: wabisabi_mob_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  get: ^4.6.6
  introduction_screen: ^3.1.14
  intl_phone_field: ^3.2.0
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.15
  pinput: ^5.0.0
  country_picker: ^2.0.27
  google_nav_bar: ^5.0.7
  percent_indicator: ^4.2.4
  fl_chart: ^0.69.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  shared_preferences: ^2.3.1
  google_fonts: ^6.2.1
  flutter_xlider: ^3.5.0
  dropdown_button2: ^2.3.9
  gradient_borders: ^1.0.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^5.0.2
  # flutter_local_notifications: ^18.0.1
  intl: ^0.20.2




  http: any
  image_picker: ^1.1.2
  file_picker: ^9.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
